[project]
name = "ragagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "unhappyh2", email = "qiuguanhua37@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dashscope>=1.26.7",
    "dotenv>=0.9.9",
    "langchain>=1.3.15",
    "langchain-community>=0.4.2",
    "langchain-deepseek>=1.1.0",
]

[project.scripts]
ragagent = "ragagent:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
